### ISSUE TITLE
fatal error: concurrent map writes

### ISSUE THREAD

**Issue by erickertz** [bbalet/stopwords#12]
this is causing a panic error under high volume:

`fatal error: concurrent map writes
goroutine 30452 [running]:
runtime.throw(0x10276a9, 0x15)
	/usr/local/go/src/runtime/panic.go:774 +0x72 fp=0xc0003fcea8 sp=0xc0003fce78 pc=0x42f1a2
runtime.mapassign_faststr(0xe7a2c0, 0xc015fe1500, 0x104e145, 0x4, 0xc0151b0e38)
	/usr/local/go/src/runtime/map_faststr.go:211 +0x417 fp=0xc0003fcf10 sp=0xc0003fcea8 pc=0x4132c7
github.com/bbalet/stopwords.LoadStopWordsFromString(0x104e101, 0xa1, 0x100b6d9, 0x2, 0x100b47b, 0x1)
	/go/pkg/mod/github.com/bbalet/stopwords@v1.0.0/custom.go:74 +0xd30 fp=0xc0003fcf98 sp=0xc0003fcf10 pc=0xd12a00
github.com/urbn/catalog-search-service/app/services.(*ProductService).GetProducts(0xc000576050, 0x7f4f63e60fc0, 0xc02521ec80, 0xc015df9400, 0x0, 0xc015e3c760, 0x1e, 0x1, 0x0, 0xc015e623b8, ...)`

**Comment by bbalet** [comment]
What is your use case ? Because you are supposed to use the function LoadStopWordsFromString once (i.e. at the initialization of your application).

**Comment by erickertz** [comment]
Thanks for your reply. I'll have to rework how I implemented this. I think it'll be a little more complicated because I'm using it in a restful service where each request has different languages.

**Comment by bbalet** [comment]
I assume that your current implementation is buggy. If you have a concurrent access to this map it means that it is stored into a shared memory space such as a global var accessed by various http handlers, e.g.:

- Handler A loads English language in global var sw
- Handler B loads Franch language and erases previous content of sw

Problem is that you have no guarantee that Handler A has finnished before Handler B erases sw's content.

Using mutexes would penalize performance and sw variable access would become your bottleneck. Maybe a goroutine per language with a local sw variable and channels would do the trick.

Can I close this issue?

**Comment by erickertz** [comment]
Thanks for the advise, yes I'll close.
