### ISSUE TITLE
Chargement des stop word à partir d'un fichier.

### ISSUE THREAD

**Issue by LeMoussel** [bbalet/stopwords#4]
_Bonjour Jacques, Comme je pense que tu es français, je me permets d'écrire cette "issue" in french  !_

Afin de procéder a des tests sur l'utilisation de stops words sur différents textes, la liste de stop words est stocké dans un ficher comprenant un stop word sur chaque ligne. Ainsi cela me permet de tester sans recomplier.

Il serait donc intéressant d'avoir une fonction avec le chemin du fichier de stop word a charger en lieu et place du code de langue. par ex. `CleanStringFile(content string, fileName string, cleanHTML bool))`

**Comment by bbalet** [comment]
Implemented by https://github.com/bbalet/stopwords/commit/a6a172105d2ac809a045fbc02db38460d4506216
